#--[################################################################]
#--[##################### GENERAL INFORMATION ######################]
#--[################################################################]

# Don't delete anything below, just edit the fields!
# General Reminder: true means yes; false means no
# If you ever feel like you have messed up and need to get the file back to its default state just delete the .yml file and restart the server
# The majority of text based fields within this file support external placeholders from PlaceholderAPI
# To edit Rewards you must edit the Rewards.yml file, none of that is done here!

# If you have any questions you can always get support at: https://discord.gg/9jyHhUepaG



#################################################################
##################### Storage Configuration #####################
#################################################################

###### Important Information ######
# ** YOU MUST RESTART YOUR SERVER AFTER CHANGING STORAGE CONFIGURATION SETTINGS, FAILURE TO DO SO CAN LEAD TO DATA LOSS AND ERRORS. **
# You can easily switch between data-storage methods and take your data with you, using our integrated /daily migrate command

# If set to true, data will be stored in a MySQL database.
# If set to false, data will be stored in a flat-file local format.
MySQL-Enabled: false

# These are your MySQL details. If you do not plan to use MySQL, leave these blank
MySQL-Login:
  Host: ""
  Port: ""
  Database: ""
  Username: ""
  Password: ""


#################################################################
##################### General Configuration #####################
#################################################################

# Whether to print detectable plugin errors to console (Recommended to leave as true for debugging reasons)
PrintErrorsToConsole: true

# The plugins prefix shown in chat commands/console outputs
PluginPrefix: "&aᴛɴ's&6ᴅᴀɪʟʏ"

# The title shown in GUI's such as the reward claiming menu
PluginGuiTitle: "&aᴛɴ's&6ᴅᴀɪʟʏ"

# Whether the plugin should check for updates
CheckForUpdates: true

# Whether the plugin should automatically delete data (custom items) that are not in use in either the Config.yml or Rewards.yml file
# Cleaning actions are irreversible, items will need to be added back again if needed.
# NOTE: It is recommended to set this to true to improve plugin speed!
CleanUnusedData: true


#################################################################
####################### Claiming Rewards ########################
#################################################################
###  NOTE: This section contains some EXPERIMENTAL FEATURES!  ###
###  Should you happen to experience any bugs when enabling;  ###
###        Please make us aware on our support discord:       ###
###              https://discord.gg/9jyHhUepaG                ###
#################################################################

# When a player reaches the day limit, should it reset their Daily Reward streak?
# If set to false the user will repeatedly be able to claim the maximum day reward until the streak is lost
ResetWhenStreakCompleted: true

# [EXPERIMENTAL FEATURE]: When set to true EVERYONE'S streak becomes available at midnight (relevant to the region your server is hosted in)
# When set to false a players streak becomes available 24 hours after claiming
AvailableOnNewDay: false

# When set to true, if a player misses a day, the streak will be preserved until they return
# NOTE: If 'PauseStreakWhenMissed' is set to true as well as 'SkipMissedDays' then 'SkipMissedDays' will automatically be made false ~ Only one or the other can be true!
PauseStreakWhenMissed: false

# [EXPERIMENTAL FEATURE]: When set to true, if a player misses a day the streak will ignore that day and skip over it when the player returns
# NOTE: If 'PauseStreakWhenMissed' is set to true as well as 'SkipMissedDays' then 'SkipMissedDays' will automatically be made false ~ Only one or the other can be true!
SkipMissedDays: false

# [EXPERIMENTAL FEATURE]: When set to true, only one user per IP, per day can claim a reward.
# This prevents users making multiple accounts to claim a reward.
# A side effect of this is multiple genuine players using the same IP won't be able to claim their reward
IPLimiter: false

# You may specify a sound effect that you wish to be played for the user when they claim a Daily Reward (through the GUI only)
# A full list of eligible sounds may be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# All sounds play through the players MASTER channel in minecraft. Set to "none" to disable the sounds
SoundEffect:
  # Sound to be played when the /daily GUI is opened
  OpenType: "NONE"
  # Sound to be played when a reward is claimed through the /daily GUI
  ClaimType: "NONE"

  Volume: 1 # Value should be >= 0
  Pitch: 1 # Value should be 0.0 - 2.0

#################################################################
###################### Daily Reward Chests ######################
#################################################################

# The effect of revealing the daily reward, available options: PopOut, GUI, Lightning, Christmas, None
DailyRewardAnimation: "PopOut"

# Make smoke pop out of the crate when opening
RedeemParticleEffects: true

# Whether there should be floating text above daily reward chests
FloatingTextAbove: false

# The text above daily reward chests if "FloatingTextAbove" is set to true, This field does not support placeholders as it is visible to everyone!
# To use placeholders in holograms above a chest we suggest switching 'FloatingTextAbove' to false and utilising the powerful plugin: HolographicDisplays
FloatingText: "<gradient:#FDE24D:#FDE24D>Re</gradient><gradient:#FDE24D:#F1B412>compens</gradient><gradient:#F1B412:#F1B412>as Diárias</gradient>"

# The format of the day used on the hologram for the Daily Reward chest
DayFormat: "[ᴅɪᴀ <day>]"


#################################################################
####################### Player Join Event #######################
#################################################################

# Whether a reward should automatically claim when a player joins (if available)
RewardAutoClaim: false

# When a player joins should the reward claim GUI pop up instantly?
RewardInstantPopup: false

# Whether players should receive a chat message reminder to claim their Daily Reward (When Available)
DailyRewardReminderEnabled: true

# How often the server should remind a player that they have a Daily Reward waiting to be claimed (In Seconds)
DailyRewardClaimReminder: 1200

# Whether players should be able to click the reward reminder message to bring up the DailyRewards+ GUI
DailyRewardReminderClickable: true

# Worlds where the daily reward reminder will NOT be sent
DailyRewardReminderBlacklistedWorlds:
  - ''

#################################################################
##################### Playtime Requirements #####################
#################################################################

# Should users be required to have a certain amount of playtime before they can start claiming rewards?
# Please note that playtime values only begin recording once this is set to true, old play-times will not be counted.
PlaytimeRequirement: false

# Whether the playtime requirement should be met every single day in order to claim rewards
# If set to false, the requirement will only need to be met once in order to claim rewards immediately on any day
RequiredDaily: true

# Prevents playtime value from incrementing if someone is detected as AFK for more than 30 seconds
AFKDetection: false

# The playtime required (in minutes) to claim rewards
PlaytimeRequired: 20


#################################################################
####################### Daily Rewards GUI #######################
#################################################################

# The amount of rows to be within the DailyRewards+ Claim GUI (Number 1-6)
# If the BottomBar setting is enabled, the bottom row will be entirely consumed by the statistics and page maneuver panel
InventoryRows: 6

# GUI reward line indent
LineIndent: "&f- "

# If set to true, Daily Reward icons within the GUI will show a quantity relating to the day of their reward (i.e., Day 5 will be an icon with quantity 5)
# If the total number of days is greater than 64, this feature is automatically disabled. Items can only stack up to 64.
ShowDayQuantity: true

# Whether the GUI should automatically close when a reward is claimed
CloseOnClaim: false

# Whether the GUI stats timer (if enabled) should live-update the time until the next reward.
# For particularly low-spec servers, it may be advisable to disable this.
LiveUpdateTimer: true

# Whether to apply the HIDE_ATTRIBUTES flag to all items within the GUI.
HideAttributes: true

# Whether the buttons in the GUI should be disabled (i.e., users can't interact with the GUI)
# It is only recommended to set this to true if you intend for users to be given rewards solely on join/through the DailyRewards+ chest.
ButtonsDisabled: false

#* Placeholders that can be used in the following section:
#* <daysReward> - The daily reward name for that day
#* <dayNum> - The rewards day number
#* <timeUntilNextReward> - The time until the next reward can be claimed
#* <playerName> - The name of the player
#* <playerStreak> - The players daily reward streak
#*
#* <rewardicon> - Can be used in Icon fields to show the Rewards.yml icon for that day instead
# This section also supports minecraft color codes and HEX color codes! (https://bit.ly/MinecraftCC)

UnclaimedReward:
  Title: "&aᴅɪᴀ <dayNum>"
  # This icon is configured on a per-day basis in the Rewards.yml file!
  Lore:
    - "&7sᴜᴀ ʀᴇᴄᴏᴍᴘᴇɴsᴀ ᴛᴇ ᴇsᴘᴇʀᴀ..."
    - "&7ᴍᴇ ᴄʟɪǫᴜᴇ ᴘᴀʀᴀ ʀᴇsɢᴀᴛᴀʀ!"
    - " "
    - "&6&lʀᴇᴄᴏᴍᴘᴇɴsᴀ(s):"
    - "<daysReward>"
    - " "
    - "&c&lʀᴇᴄᴏᴍᴘᴇɴsᴀ ᴅɪsᴘᴏɴɪᴠᴇʟ!"

RewardNotReady:
  Title: "&cᴅɪᴀ <dayNum>"
  Icon: "COAL_BLOCK"
  Enchanted: true
  Lore:
    - "&7Sᴜᴀ ʀᴇᴄᴏᴍᴘᴇɴsᴀ ᴇsᴛᴀʀᴀ ᴀǫᴜɪ ᴇᴍ ʙʀᴇᴠᴇ..."
    - "&7ᴀɢᴜᴀʀᴅᴇ <timeUntilNextReward>"
    - " "
    - "&6&lʀᴇᴄᴏᴍᴘᴇɴsᴀs(s):"
    - "<daysReward>"
    - " "
    - "&c&lRᴇᴄᴏᴍᴘᴇɴsᴀ ᴄʜᴇɢᴀɴᴅᴏ!"

MissedReward:
  Title: "&c&l[ᴘᴇʀᴅɪᴅᴏ] &cᴅɪᴀ <dayNum>"
  Icon: "COAL_BLOCK"
  Enchanted: false
  Lore:
    - "&7ᴠᴏᴄᴇ ᴘᴇʀᴅᴇᴜ sᴜᴀ ʀᴇᴄᴏᴍᴘᴇɴsᴀ"
    - "&7ɴᴀᴏ sᴇ ᴘʀᴇᴏᴄᴜᴘᴇ, ᴍᴀɪs ᴛᴇ ᴀɢᴜᴀʀᴅᴀᴍ!"
    - " "
    - "&6&lRᴇᴄᴏᴍᴘᴇɴsᴀs(s):"
    - "<daysReward>"
    - " "
    - "&c&lʀᴇᴄᴏᴍᴘᴇɴsᴀ ᴘᴇʀᴅɪᴅᴀ!"

ClaimedReward:
  Title: "&bDɪᴀ <dayNum>"
  Icon: "EMERALD_BLOCK"
  Enchanted: false
  Lore:
    - "&7ᴍᴀɪs ʀᴇᴄᴏᴍᴘᴇɴsᴀs ᴛᴇ ᴀɢᴜᴀʀᴅᴀᴍ,"
    - "&7ʟᴏɢᴜᴇ ᴅɪᴀʀᴀᴍᴇɴᴛᴇ ᴘᴀʀᴀ ᴘᴇɢᴀʀ ᴍᴀɪs ᴘʀᴇᴍɪᴏs!"
    - " "
    - "&6&lReᴄᴏᴍᴘᴇɴsᴀ(s):"
    - "<daysReward>"
    - " "
    - "&a&lReᴄᴏᴍᴘᴇɴsᴀ ʀᴇsɢᴀᴛᴀᴅᴀ!"

FutureReward:
  Title: "&cDɪᴀ <dayNum>"
  Icon: "COAL_BLOCK"
  Enchanted: false
  Lore:
    - "&7ᴛᴇɴʜᴀ ᴜᴍᴀ sᴇǫᴜᴇɴᴄɪᴀ ᴅᴇ <dayNum> ᴅɪᴀs"
    - "&7ᴘᴀʀᴀ ᴀᴄᴇssᴀʀ ᴇsᴛᴇ ᴘʀᴇᴍɪᴏ!"
    - ""
    - "&6&lʀᴇᴄᴏᴍᴘᴇɴsᴀ(s):"
    - "<daysReward>"

# This is the standard item that will fill the empty slots in the primary area of the GUI
# The title " " should be used to represent no text.
Placeholder:
  Title: " "
  Icon: "GRAY_STAINED_GLASS_PANE"   # Set to "AIR" for no background

# This is the item that is used by players to visit the previous page. It will only be showed if there is a previous page available
# The text placeholder <pg> is used to represent the previous page number. The placeholder <tot> is used to represent the total number of pages.
PreviousPage:
  Active: true
  GUI Position: 45
  Icon: "ARROW"
  Title: "&3ᴘʀᴏxɪᴍᴀ ᴘᴀɢɪɴᴀ &f[<pg>/<tot>]"
  Lore:
    - '&7ᴄʟɪǫᴜᴇ ᴘᴀʀᴀ ɪʀ ᴘᴀʀᴀ ᴀ ᴘʀᴏxɪᴍᴀ ᴘᴀɢɪɴᴀ.'

# This is the item used to show the users streak and time until next reward.
# This can be disabled if not required for your server.
Statistics:
  Active: true
  GUI Position: 49
  Icon: "<phead>"   ### Can be set to any minecraft item, however use <phead> as a placeholder for the players head.
  Title: "&3ʀᴇᴄᴏᴍᴘᴇɴsᴀs ᴅɪᴀʀɪᴀs ᴅᴇ <playerName>"
  Lore:
    - "&bsᴇǫᴜᴇɴᴄɪᴀ: &f<playerStreak> ᴅɪᴀ(s)"
    - "&bᴘʀᴏxɪᴍᴀ ʀᴇᴄᴏᴍᴘᴇɴsᴀ: &f<timeUntilNextReward>"

# This is the item that is used by players to visit the next page. It will only be showed if there is a next page available
# The text placeholder <pg> is used to represent the next page number. The placeholder <tot> is used to represent the total number of pages.
NextPage:
  Active: true
  GUI Position: 53
  Icon: "ARROW"
  Title: "&3ᴘʀᴏxɪᴍᴀ ᴘᴀɢɪɴᴀ&f[<pg>/<tot>]"
  Lore:
    - "&7ᴄʟɪǫᴜᴇ ᴘᴀʀᴀ ɪʀ ᴘᴀʀᴀ ᴀ ᴘʀᴏxɪᴍᴀ ᴘᴀɢɪɴᴀ."


# This is an additional (optional) field that allows you to insert additional items into the GUI
# To add an item to the GUI, add a line to the list below and configure it with the following available fields:
#* pos= : This is the position of the item in the GUI, note 0 is the top-left of the GUI.
#* page= : This is the page of the GUI the item should be displayed on, set to # to be shown on all pages.
#* item= : This is the namespaced ID of the material to use for the item.
#* qty= : This is the quantity of items (1-64).
#* enchanted= : This is true/false whether the item should be enchanted or not.
#* cmi= : This is the custom model ID to be applied to the item (if applicable).
#* command="" : This is the command to be ran when a user clicks the item.
#* name="" : This is the name of the item in the GUI (blank if not included)
#* lore="" : This is the lore of the item in the GUI, Use " - " to add new lines, for example; lore="line1 - line2 - line3" (blank if not included)
Additional GUI Items:
  - 'pos=45 page=# item=BLACK_STAINED_GLASS_PANE qty=1 enchanted=false'
  - 'pos=46 page=# item=BLACK_STAINED_GLASS_PANE qty=1 enchanted=false'
  - 'pos=47 page=# item=BLACK_STAINED_GLASS_PANE qty=1 enchanted=false'
  - 'pos=48 page=# item=BLACK_STAINED_GLASS_PANE qty=1 enchanted=false'
  - 'pos=49 page=# item=BLACK_STAINED_GLASS_PANE qty=1 enchanted=false'
  - 'pos=50 page=# item=BLACK_STAINED_GLASS_PANE qty=1 enchanted=false'
  - 'pos=51 page=# item=BLACK_STAINED_GLASS_PANE qty=1 enchanted=false'
  - 'pos=52 page=# item=BLACK_STAINED_GLASS_PANE qty=1 enchanted=false'
  - 'pos=53 page=# item=BLACK_STAINED_GLASS_PANE qty=1 enchanted=false'